### PR TITLE
Tt

### PR DESCRIPTION
**Pull request by xkyu**
tt

### CODE REVIEW

**Comment by xkyu** [comment]
tt

**Comment by xkyu** [comment]
ttx
asdf
23
a

**Comment by xkyu** [comment]
1

**Comment by xkyu** [comment]
1

**Comment by xkyu** [comment]
a\nb\nc

**Comment by xkyu** [comment]
def

**Comment by xkyu** [comment]
long title
long description

**Comment by xkyu** [comment]
failed. [1]

**Comment by xkyu** [comment]
failed. [1]

**Comment by xkyu** [comment]
failed. [127]

**Comment by xkyu** [comment]
There are 127 failed Testcases on this test. Please check the [log](https://travis-ci.org/xkyu/cubrid/builds/238632699) on Travis

**Comment by xkyu** [comment]
There are 1 failed Testcases. Please check the [log](https://circleci.com/gh/xkyu/cubrid/20)

**Comment by xkyu** [comment]
There are 1 failed Testcases. Please check the [log](https://circleci.com/gh/xkyu/cubrid/24)

**Comment by xkyu** [comment]
There are 1 failed Testcases. Please check the [log](https://circleci.com/gh/xkyu/cubrid/25).

**Comment by cubridci** [comment]
x

**Comment by xkyu** [comment]
x

**Pull request closed without merging**
